# Docker Compose file for a basic Quanta Distro, which packages the MongoDB and App together.
# (for now IPFS is omitted)

version: '3.7'
services:
    # IMPORTANT: Uncomment this block to enable IPFS
    # https://hub.docker.com/r/ipfs/go-ipfs/
    # NOTES: To run a prodution IPFS instance be sure port 4001 is open
    # and set the IPFS_PROFILE to "server"
    # 4001 is swarm port required to connect IPFS to outside world. Don't forget to open up 
    # this port in your firewall (and ISP/Router configs)
    ipfs-distro: 
        deploy:
            resources:
              limits:
                cpus: '0.15'
        container_name: ipfs-distro 
        environment:
            # IPFS_PROFILE options (lowpower | server)
            IPFS_PROFILE: "server" 
            IPFS_PATH: "/data/ipfs"
            # LIBP2P_FORCE_PNET: 1
        expose:
            - '4001'
        #     - '8081'
        #     - '5001'
        # WARNING: volumes will not handle '~' character for home folder. Do not use.
        volumes:
            - '${ipfs_staging}:/export'
            - '${ipfs_data}:/data/ipfs'
        ports:
            - "4001:4001"
            # - "127.0.0.1:8080:8080"
            # - "127.0.0.1:8081:8081"
            # - "127.0.0.1:5001:5001"
        networks:
            - net-distro
        image: ipfs/go-ipfs:v0.12.2

# https://docs.docker.com/compose/networking/
networks:
  net-distro:
    driver: bridge
    external: false
    name: net-distro

