# Docker Compose file for a basic Quanta Distro, which packages the MongoDB and App together.
# (for now IPFS is omitted)

version: '3.7'
services:
    mongo-distro: 
        container_name: mongo-distro 
        # WARNING: volumes will not handle '~' character for home folder. Do not use.
        volumes:
            - "${MONGO_DATA}:/data/db"
            - "${DEPLOY_TARGET}/dumps:/dumps"
            # - "${MONGO_SCRIPTS}:/mongo-scripts"
            - "${MONGOD_CONF}:/etc/mongod.conf"
        command: mongod --config /etc/mongod.conf
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${adminPassword}
        networks:
            - net-distro
        # Always specify version of mongo. When it upgrades automatically there can be database issues that need to be resolved
        # and we don't want that happening unexpectedly
        image: mongo:4.0

# https://docs.docker.com/compose/networking/
networks:
  net-distro:
    driver: bridge
    external: false
    name: net-distro

