# Docker Compose (for Development) 
version: '3.7'
services:
    redis-dev:
        image: redis:6.0
        deploy:
            restart_policy:
                condition: on-failure
                # delay is time between restart attempts
                delay: 10s
                max_attempts: 4
                window: 120s
            replicas: 1
        hostname: redis-host-dev
        networks:
            bridge:
                aliases:
                    - redis-host-dev
        # No need to limit resources for now
        # deploy:
        #     resources:
        #         limits:
        #             cpus: '0.50'
        #             memory: 128M
        #         reservations:
        #             cpus: '0.25'
        #             memory: 64M
        ports:
            - "${REDIS_PORT}:${REDIS_PORT}"
        
        # Saves to disk every 20 seconds (if 1 or more writes done)
        # command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        # mem arg: --maxmemory 50M

        command: redis-server --maxmemory-policy allkeys-lru --port ${REDIS_PORT} --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        environment:
            REDIS_HOST: "${REDIS_HOST}"
            REDIS_PORT: "${REDIS_PORT}"
            REDIS_PASSWORD: ${REDIS_PASSWORD}
            
        # We need to embed the AppVersion into the Redis Records before it makes sense
        # to cache them across restarts.
        # volumes: 
        #     - ${QUANTA_BASE}/redis:/data

    mongo-dev: 
        # Warning: supposedly starting at Mongo 6.0 this would be the way to do healthcheck
        #   test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
        #      --or--
        #   test: ["CMD","mongosh", "--eval", "db.adminCommand('ping')"]

        image: mongo:6.0.8
        deploy:
            restart_policy:
                condition: on-failure
                # delay is time between restart attempts
                delay: 10s
                max_attempts: 4
                window: 120s
            replicas: 1
        hostname: mongo-host-dev
        networks:
            bridge:
                aliases:
                    - mongo-host-dev
       
        volumes:
            - '${MONGO_BASE}/mongodb-data-dev:/data/db'
            - '${MONGOD_CONF}:/etc/mongod.conf'
            - '${MONGO_BACKUP}:/backup'

        command: mongod --config /etc/mongod.conf

        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${mongoPassword}

        # healthcheck:
        #     test: echo 'db.runCommand("ping").ok' | mongo mongo:27016/test --quiet
        #     interval: 10s
        #     timeout: 10s
        #     retries: 5
        #     start_period: 40s

    # ipfs-dev: 
    #     # https://hub.docker.com/r/ipfs/kubo/
    #     image: ipfs/kubo:release
    #     hostname: ipfs-host-dev
    #     networks:
    #         bridge:
    #             aliases:
    #                 - ipfs-host-dev
    #     deploy:
    #         resources:
    #             limits:
    #                 # Give docker 10% of CPU and 1 GB max
    #                 cpus: "0.1"
    #                 memory: 1000M
    #             # reservations:
    #             #   cpus: 0.25
    #             #   memory: 128M

    #     environment:
    #         # IPFS_PROFILE options (lowpower | server)
    #         IPFS_PROFILE: "server" 
    #         IPFS_PATH: "/data/ipfs"
        
    #     volumes:
    #         - '${ipfs_staging}:/export'
    #         - '${ipfs_data}:/data/ipfs'

    #     ports:
    #         # Allow this thru your firewall: sudo ufw allow 4001
    #         - "4001:4001"
    #         - "4001:4001/udp"

    quanta-dev:
        image: ${DOCKER_IMAGE}
        build: 
            context: ${PRJROOT}
            args:
                PORT: "${PORT}"
                PORT_DEBUG: "${PORT_DEBUG}"
                XMS: "${XMS}"
                XMX: "${XMX}"
            dockerfile: ./dockerfile-dev

        # This is important for DEV environment because we have a script
        # we run to deploy new Java Classes, and it works by scaling down
        # to zero replicas, doing a build, and then scaling back up, so
        # we don't want docker swarm on it's own restarting it during all that.
        # restart: "no"

        # =================================================================
        # DEPLOY REPLICAS
        # Enable either one of the two deploy sections below
        # =================================================================
        # deploy for normal development with single replia
        # NOTE: If you don't need Zero Downtime deploy you can just set multiple replias here
        deploy:
            restart_policy:
                condition: on-failure
                # delay is time between restart attempts
                delay: 10s
                max_attempts: 4
                window: 120s
            replicas: 1
        # =================================================================
        # This config does a Zero-Downtime Redeploy!!
        # deploy:
        #     replicas: 2
        #     update_config:
        #         parallelism: 1
        #         order: start-first
        #         failure_action: rollback
        #         delay: 10s
        #     rollback_config:
        #         parallelism: 0
        #         order: stop-first
        #     restart_policy:
        #         condition: any
        #         delay: 5s
        #         max_attempts: 3
        #         window: 120s
        # healthcheck:
        #     test: ["CMD", "curl", "-f", "http://quanta-host:${PORT}/health"]
        #     # interval: 3m
        #     # timeout: 10s
        #     # retries: 3
        #     # start_period: 20s
        # ====================================================================

        hostname: quanta-host
        networks:
            bridge:
                aliases:
                    - quanta-host
        volumes:
            - '${QUANTA_BASE}/tmp:/tmp'
            - '${QUANTA_BASE}/log:/log'
            - '${QUANTA_BASE}/config:/config'
            - '${QUANTA_BASE}/lucene:/subnode-lucene'
            - '${PRJROOT}/src/main/resources/public:/dev-resource-base'
            - '${PRJROOT}/target/classes:/loader-path'
            
        ports:
            - '${HOST_PORT}:${PORT}'
            - '${PORT_DEBUG}:${PORT_DEBUG}'

        environment:
            # Docker warm vars
            X_NODE_ID: "{{.Node.ID}}"
            X_NODE_HOSTNAME: '{{.Node.Hostname}}'
            X_SERVICE_ID: '{{.Service.ID}}'
            X_SERVICE_NAME: '{{.Service.Name}}'
            X_TASK_SLOT: "{{.Task.Slot}}"
            X_TASK_ID: '{{.Task.ID}}'
            X_TASK_NAME: '{{.Task.Name}}'

            QUANTA_VER: "${QUANTA_VER}"
            logging.config: /log/logback.xml
            XMS: "${XMS}"
            XMX: "${XMX}"

            REDIS_HOST: "${REDIS_HOST}"
            REDIS_PORT: "${REDIS_PORT}"
            REDIS_PASSWORD: "${REDIS_PASSWORD}"
            
            # Can be a comma-delimited list of TestIntf-derived tests to run
            # examples are "LangTest,UtilsTest,MongoTest,MongoFediverseNamesTest,IPFSTest,SchemaOrgTest"
            # **** Tip ****: remember to put this line in setenv-dev.sh if running IPFS tests: `export ipfsEnabled="true"`
            runTests:
            
            adminPassword: "${adminPassword}"
            mongoPassword: "${mongoPassword}"
            mongoSecurity: "true"

            # WARNING: Most browsers (other than Firefox) will not support crypto unless you're on HTTPS
            # requireCrypto: "true"

            # NOTE: '>-' removes all newline characters and makes one long string
            # Using '|' there instead would preserve the newlines after read in
            # The '-' after either of those removes any trailing newline
            testUserAccounts: >-
                FollowBot:${adminPassword}:${devEmail},
                adam:${testPassword}:${devEmail},
                bob:${testPassword}:${devEmail},
                cory:${testPassword}:${devEmail},
                dan:${testPassword}:${devEmail},
                eric:${testPassword}:${devEmail}
    
            testPassword: "${testPassword}"
            throttleTime: "0"
            spring.config.location: "classpath:/application.properties" 
            mongodb.host: "${MONGO_HOST}"
            mongodb.port: "${MONGO_PORT}" 
            instanceId: "dev"
            profileName: "dev"
            server.port: "${PORT}" 
            httpProtocol: "http" 
            metaHost: "${quanta_domain}" 
            allowFileSystemSearch: "false"
            actPubEnabled: "false"

            ipfsEnabled: "${ipfsEnabled}"
            spring.http.multipart.max-file-size: "200MB" 
            spring.http.multipart.max-request-size: "200MB" 
            spring.servlet.multipart.max-file-size: "200MB"
            spring.servlet.multipart.max-request-size: "200MB"
            adminDataFolder: "/tmp" 

            mail.port: ""
            mail.user: "postmaster@quantizr.com" 
            mail.password: "${emailPassword}" 
            mail.host: "smtp.mailgun.org" 
            mail.from: "admin@quanta.wiki"

            JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:${PORT_DEBUG},server=y,suspend=n"
            
            ipfs.host: "http://ipfs-host-dev"
            ipfs.apiPort: "5001"
            ipfs.gatewayPort: "8080"

networks:
    bridge:
