# Docker Compose file for a basic Quanta Distro, which packages the MongoDB and App together.
# (for now IPFS is omitted)

version: '3.7'
services:
    quanta-distro:
        # When we're not doing a docker build this build section will sit here harmlessly not being used.
        build: 
           context: .
           dockerfile: dockerfile

        container_name: quanta-distro
        expose:
            - "${PORT}"
            # Uncomment for debugging...
            #- '8000'
        # WARNING: volumes will not handle '~' character for home folder. Do not use.
        volumes:
            - "${DEPLOY_TARGET}/tmp:/tmp"
            - "${DEPLOY_TARGET}/log:/log"
            - '${DEPLOY_TARGET}/config:/config'
            # - $PWD:/app
        ports:
            - "${PORT}:${PORT}"
            # Uncomment for debugging...
            #- '8000:8000'
        networks:
            - net-distro
        environment:
            logging.config: /log/logback.xml
            XMS: "${XMS}"
            XMX: "${XMX}"
            mongoAdminPassword: "${adminPassword}"
            mongoSecurity: "true"

            # NOTE: '>-' removes all newline characters and makes one long string
            testUserAccounts: >- 
                FollowBot:${adminPassword}:${devEmail},
                adam:${testPassword}:${devEmail},
                bob:${testPassword}:${devEmail},
                cory:${testPassword}:${devEmail},
                dan:${testPassword}:${devEmail}

            spring.config.location: "classpath:/application.properties" 
            mongodb.host: "${MONGO_HOST}" 
            mongodb.port: "${MONGO_PORT}" 
            profileName: "prod" 
            instanceId: "prod"
            server.port: "${PORT}" 
            httpProtocol: "http" 
            metaHost: "${quanta_domain}" 
            allowFileSystemSearch: "false" 
            actPubEnabled: "false"
            spring.http.multipart.max-file-size: "200MB" 
            spring.http.multipart.max-request-size: "200MB" 
            spring.servlet.multipart.max-file-size: "200MB"
            spring.servlet.multipart.max-request-size: "200MB"
            adminDataFolder: "/tmp" 

            # Uncomment for debugging... (don't forget to open ufw firewall for port on server)
            #JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:8000,server=y,suspend=n"
            
            ipfs.host: "http://ipfs-distro"
            ipfs.apiPort: "5001"
            ipfs.gatewayPort: "8080"
        
        image: subnode/repo:quanta${QUANTA_VER}
        # depends_on:
        #     - mongo-distro
            # IMPORTANT: Uncomment this line to enable IPFS
            # - ipfs-distro

# https://docs.docker.com/compose/networking/
networks:
  net-distro:
    driver: bridge
    external: false
    name: net-distro

