# Docker Compose file for a basic Quanta Distro
# (for now IPFS is omitted)

version: '3.7'
services:

    mongo-distro: 
        container_name: mongo-distro 
        # WARNING: volumes will not handle '~' character for home folder. Do not use.
        volumes:
            - "${MONGO_DATA}:/data/db"
            - "${DEPLOY_TARGET}/dumps:/dumps"
            - "${MONGOD_CONF}:/etc/mongod.conf"
        command: mongod --config /etc/mongod.conf
        ports:
            - "${MONGO_PORT}:${MONGO_PORT}"
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${subnodePassword}
        networks:
            - net-distro
        # Always specify version of mongo. When it upgrades automatically there can be database issues that need to be resolved
        # and we don't want that happening unexpectedly
        image: mongo:4.0

    quanta-distro:
        
        # When we're not doing a docker build this build section will sit here harmlessly not being used.
        build: 
           context: .
           dockerfile: dockerfile

        container_name: quanta-distro
        expose:
            - "${PORT}"
            # Uncomment for debugging...
            #- '8000'
        # WARNING: volumes will not handle '~' character for home folder. Do not use.
        volumes:
            - "${DEPLOY_TARGET}/tmp:/tmp"
            - "${DEPLOY_TARGET}/log:/log"
            - '${DEPLOY_TARGET}/config:/config'

             # This maps '/app' to be the current folder where you run docker from (where the yaml file is normally)
            - $PWD:/app
        ports:
            - "${PORT}:${PORT}"
            # Uncomment for debugging...
            #- '8000:8000'
        networks:
            - net-distro
        environment:
            XMS: "${XMS}"
            XMX: "${XMX}"
            mongoAdminPassword: "${subnodePassword}"
            mongoSecurity: "true"

            # NOTE: '>-' removes all newline characters and makes one long string
            testUserAccounts: >- 
                adam:${testPassword}:${devEmail},
                bob:${testPassword}:${devEmail},
                cory:${testPassword}:${devEmail},
                dan:${testPassword}:${devEmail}

            spring.config.location: "classpath:/application.properties" 
            mongodb.host: "${MONGO_HOST}" 
            mongodb.port: "${MONGO_PORT}" 
            profileName: "prod" 
            server.port: "${PORT}" 
            httpProtocol: "http" 
            metaHost: "${quanta_domain}" 
            reSaveAll: "false"
            forceIndexRebuild: "false"
            allowFileSystemSearch: "false" 
            actPubEnabled: "false"
            spring.http.multipart.max-file-size: "200MB" 
            spring.http.multipart.max-request-size: "200MB" 
            spring.servlet.multipart.max-file-size: "200MB"
            spring.servlet.multipart.max-request-size: "200MB"
            adminDataFolder: "/tmp" 

            # Uncomment for debugging... (don't forget to open ufw firewall for port on server)
            #JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:8000,server=y,suspend=n"
            
            xxxipfs.host: "http://ipfs-test"
            xxxipfs.apiPort: "5001"
            xxxipfs.gatewayPort: "8080"
        
        image: subnode/repo:quanta${QUANTA_VER}
        depends_on:
            - mongo-distro
            # - ipfs-distro

# https://docs.docker.com/compose/networking/
networks:
  net-distro:
    driver: bridge
    external: false
    name: net-distro

