# Builder stage
FROM python:3.12.3-slim AS builder
WORKDIR /app/QuantaAI

# Copy and install requirements first to leverage caching
COPY QuantaAI/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Final stage
FROM python:3.12.3-slim
LABEL maintainer="wclayf@gmail.com"
ARG QAI_HOST
ARG QAI_PORT

# Copy installed packages from builder stage
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Set up the directory structure
WORKDIR /app

# Copy application code
COPY common ./common
COPY QuantaAI ./QuantaAI

# Set the working directory to QuantaAI where quanta_ai.py is located
WORKDIR /app/QuantaAI

# Run the uvicorn server
CMD uvicorn quanta_ai:app --host ${QAI_HOST} --port ${QAI_PORT}
