FROM openjdk:11-jre
LABEL maintainer="wclayf@gmail.com"

WORKDIR /subnode

EXPOSE 8181

COPY ./org.subnode-0.0.1-SNAPSHOT.jar /subnode/app.jar
RUN sh -c 'touch /subnode/app.jar' 

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/subnode/app.jar"]
CMD ["-Xms512m", "-Xmx2500m"]
