# WE include all of JRE which is huge but in the future we can do something like this:
# https://stackoverflow.com/questions/53669151/java-11-application-as-lightweight-docker-image

FROM openjdk:11-jre
LABEL maintainer="wclayf@gmail.com"

# Note: Args cannot be set during final runtime!
ARG PORT
ARG PORT_DEBUG
ARG JAR_FILE

# todo-0: I haven't proven yet that these values ARE being activated at runtime rather than image
# build time, but according to the memory dialog in the app these ENV vars are NOT able to
# be overridden by what's in the docker compose yaml. Need to figure this out.
ENV XMS 500m
ENV XMX 2500m

WORKDIR /quanta

EXPOSE ${PORT}
EXPOSE ${PORT_DEBUG}

COPY ${JAR_FILE} /quanta/app.jar
RUN sh -c 'touch /quanta/app.jar' 

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/quanta/app.jar"]
CMD ["-Xms${XMS}", "-Xmx${XMX}"]
