FROM openjdk:11-jre
LABEL maintainer="wclayf@gmail.com"

RUN mkdir -p /subnode-tmp
RUN echo "SubNode temp folder" > /subnode-tmp/readme.md

RUN mkdir -p /subnode-log
RUN echo "SubNode log folder" > /subnode-log/readme.md

RUN mkdir -p /dev-resource-base
RUN echo "SubNode resources" > /dev-resource-base/readme.md

RUN mkdir -p /loader-path
RUN echo "SubNode classes" > /loader-path/readme.md

WORKDIR /subnode

EXPOSE 8182
EXPOSE 8000

ADD target/org.subnode-0.0.1-SNAPSHOT.jar /subnode/subnode.jar
RUN sh -c 'touch /subnode/subnode.jar' 
VOLUME ["/subnode-tmp", "/subnode-log"]

ENTRYPOINT ["java", "-Dloader.path=/loader-path", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/subnode/subnode.jar"]
CMD ["-Xms512m", "-Xmx2500m"]
