# Builder stage
FROM python:3.12.3-slim AS builder
WORKDIR /app/QuantaAI

RUN pip install --no-cache-dir -U \
    uvicorn \
    fastapi \
    langchain \
    langchain-anthropic \
    langchain_google_genai \
    langchain-openai \
    langchain-community \
    langchain-core \
    langchain-text-splitters \
    langgraph \
    pydantic \
    pydantic_core 

# Final stage
FROM python:3.12.3-slim
LABEL maintainer="wclayf@gmail.com"
ARG QAI_HOST
ARG QAI_PORT

# Copy installed packages from builder stage
COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

# Set up the directory structure
WORKDIR /app

# Copy application code
COPY common ./common
COPY QuantaAI ./QuantaAI

# Set the working directory to QuantaAI where quanta_ai.py is located
WORKDIR /app/QuantaAI

# Run the uvicorn server
CMD uvicorn quanta_ai:app --host ${QAI_HOST} --port ${QAI_PORT}
