# NOTE: Don't try 'slim' jdk. It's missing the code for our captcha image generation
# and possibly other things
FROM openjdk:17
LABEL maintainer="wclayf@gmail.com"

ARG PORT
ARG PORT_DEBUG
ARG JAR_FILE
ARG XMS
ARG XMX

RUN mkdir -p /dev-resource-base
RUN echo "dummy" > /dev-resource-base/dummy.txt

RUN mkdir -p /loader-path
RUN echo "dummy" > /loader-path/dummy.txt

EXPOSE ${PORT}
EXPOSE ${PORT_DEBUG}

# for IPFS...
# EXPOSE 4001
# # Swarm UDP; should be exposed to the public
# EXPOSE 4001/udp

COPY ${JAR_FILE} app.jar
RUN sh -c 'touch app.jar' 

COPY ./entrypoint-dev.sh entrypoint-dev.sh
RUN ["chmod", "+x", "entrypoint-dev.sh"]
ENTRYPOINT ["./entrypoint-dev.sh"]

# I had this format for a long time, but then noticed IPFS container was failing finding /bin/bash so I moved to the simpler shell script command above
# ENTRYPOINT ["/bin/bash", "-c", "/quanta/entrypoint-dev.sh"]

# This works too but it's more flexible to just put the commands in 'entrypoint-dev.sh'
# ENTRYPOINT ["/bin/bash", "-c", "java -Xms${XMS} -Xmx${XMX} -Dloader.path=/loader-path -Djava.security.egd=file:/dev/./urandom -jar /quanta/app.jar"]
