FROM openjdk:11-jre
LABEL maintainer="wclayf@gmail.com"

ARG PORT
ARG PORT_SEC
ARG PORT_DEBUG
ARG JAR_FILE
ARG XMS
ARG XMX

WORKDIR /quanta

EXPOSE ${PORT}
EXPOSE ${PORT_SEC}
EXPOSE ${PORT_DEBUG}

COPY ${JAR_FILE} /quanta/app.jar
RUN sh -c 'touch /quanta/app.jar' 

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/quanta/app.jar"]
CMD ["-Xms${XMS}", "-Xmx${XMX}"]
