FROM openjdk:11-jre
LABEL maintainer="wclayf@gmail.com"

RUN mkdir -p /dev-resource-base
RUN echo "SubNode resources" > /dev-resource-base/readme.md

RUN mkdir -p /loader-path
RUN echo "SubNode classes" > /loader-path/readme.md

WORKDIR /subnode

# Instead of having a second dockerfile just for opening port 8182 vs 8183 let's just open both always,
# but there's never any one app instance that needs BOTH these ports open.
EXPOSE 8182
EXPOSE 8183

EXPOSE 8000

ADD target/org.subnode-0.0.1-SNAPSHOT.jar /subnode/subnode.jar
RUN sh -c 'touch /subnode/subnode.jar' 
# VOLUME ["/subnode-tmp", "/subnode-log"]

ENTRYPOINT ["java", "-Dloader.path=/loader-path", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/subnode/subnode.jar"]
CMD ["-Xms512m", "-Xmx2500m"]
