FROM ipfs/go-ipfs:v0.9.1

WORKDIR /ipfs

EXPOSE 4001
# Swarm UDP; should be exposed to the public
EXPOSE 4001/udp

# NOTE: On production we do NOT open port 5001. This file you are now reading is not used
# in production.
EXPOSE 5001

COPY ./entrypoint-ipfs.sh /ipfs/entrypoint-ipfs.sh
RUN ["chmod", "+x", "/ipfs/entrypoint-ipfs.sh"]
ENTRYPOINT ["/ipfs/entrypoint-ipfs.sh"]

# I had this format for a long time, but then noticed IPFS container was failing finding /bin/bash so I moved to the simpler shell script command above
# ENTRYPOINT ["/bin/bash", "-c", "/ipfs/entrypoint-ipfs.sh"]


