FROM openjdk:11-jre
LABEL maintainer="wclayf@gmail.com"

WORKDIR /subnode

EXPOSE 8181

ADD target/org.subnode-0.0.1-SNAPSHOT.jar /subnode/subnode.jar
RUN sh -c 'touch /subnode/subnode.jar' 

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/subnode/subnode.jar"]
CMD ["-Xms3000m", "-Xmx6000m"]
