FROM openjdk:11-jre
LABEL maintainer="wclayf@gmail.com"

ARG JAR_FILE
ARG PORT
ARG PORT_DEBUG
ARG XMS
ARG XMX

WORKDIR /quanta

EXPOSE ${PORT}

COPY ${JAR_FILE} /quanta/app.jar
RUN sh -c 'touch /quanta/app.jar' 

ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/quanta/app.jar"]
CMD ["-Xms${XMS}", "-Xmx${XMX}"]
