# NOTE: This file was part of an experiment to get Quanta working
# on kubernetes and is not successfully running yet.
apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-dev-app--out.yaml -o k8-dev-app.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: quanta-dev
      name: quanta-dev
    spec:
      type: LoadBalancer
      ports:
        - name: "8182"
          port: 8182
          targetPort: 8182
        - name: "8000"
          port: 8000
          targetPort: 8000
        # - name: 8182-tcp
        #   port: 8182
        #   targetPort: 8182
        # - name: 8000-tcp
        #   port: 8000
        #   targetPort: 8000
      selector:
        io.kompose.service: quanta-dev
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose-dev-app--out.yaml -o k8-dev-app.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: quanta-dev
      name: quanta-dev
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: quanta-dev
      strategy:
        type: Recreate
      template:
        metadata:
          annotations:
            kompose.cmd: kompose convert -f docker-compose-dev-app--out.yaml -o k8-dev-app.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.network/net-dev: "true"
            io.kompose.service: quanta-dev
        spec:
          containers:
            - env:
                - name: JAVA_TOOL_OPTIONS
                  value: -agentlib:jdwp=transport=dt_socket,address=0.0.0.0:8000,server=y,suspend=n
                - name: XMS
                  value: 512m
                - name: XMX
                  value: 4g
                - name: actPubEnabled
                  value: "false"
                - name: adminDataFolder
                  value: /tmp
                - name: allowFileSystemSearch
                  value: "false"
                - name: httpProtocol
                  value: http
                - name: instanceId
                  value: dev
                - name: ipfs.apiPort
                  value: "5001"
                - name: ipfs.gatewayPort
                  value: "8080"
                - name: ipfs.host
                  value: http://ipfs-dev
                - name: mail.from
                  value: admin@quanta.wiki
                - name: mail.host
                  value: smtp.mailgun.org
                - name: mail.password
                  value: c613da1a69375c3dcb1ea5c5c46d6218-5645b1f9-a99b979d
                - name: mail.port
                - name: mail.user
                  value: postmaster@quantizr.com
                - name: metaHost
                  value: localhost
                - name: mongoAdminPassword
                  value: TrojMajVel24x
                - name: mongoSecurity
                  value: "true"
                - name: mongodb.host
                  value: mongo-dev
                - name: mongodb.port
                  value: "27016"
                - name: profileName
                  value: dev
                - name: rssAggregatePreCacheNodeId_XX
                  value: :podcast-set
                - name: server.port
                  value: "8182"
                - name: spring.config.location
                  value: classpath:/application.properties
                - name: spring.http.multipart.max-file-size
                  value: 200MB
                - name: spring.http.multipart.max-request-size
                  value: 200MB
                - name: spring.servlet.multipart.max-file-size
                  value: 200MB
                - name: spring.servlet.multipart.max-request-size
                  value: 200MB
                - name: testPassword
                  value: ucantevenguessit
                - name: testUserAccounts
                  value: adam:ucantevenguessit:wclayf@gmail.com, bob:ucantevenguessit:wclayf@gmail.com, cory:ucantevenguessit:wclayf@gmail.com, dan:ucantevenguessit:wclayf@gmail.com, eric:ucantevenguessit:wclayf@gmail.com
                - name: throttleTime
                  value: "0"
              image: quanta-dev
              imagePullPolicy: Never
              name: quanta-dev
              ports:
                - containerPort: 8182
                - containerPort: 8000
                - containerPort: 8182
                - containerPort: 8000
              resources: {}
              volumeMounts:
                - mountPath: /tmp
                  name: quanta-dev-claim0
                - mountPath: /log
                  name: quanta-dev-claim1
                - mountPath: /config
                  name: quanta-dev-claim2
                - mountPath: /subnode-lucene
                  name: quanta-dev-claim3
                - mountPath: /dev-resource-base
                  name: quanta-dev-claim4
                - mountPath: /loader-path
                  name: quanta-dev-claim5
                - mountPath: /app
                  name: quanta-dev-claim6
          restartPolicy: Always
          volumes:
            - name: quanta-dev-claim0
              persistentVolumeClaim:
                claimName: quanta-dev-claim0
            - name: quanta-dev-claim1
              persistentVolumeClaim:
                claimName: quanta-dev-claim1
            - name: quanta-dev-claim2
              persistentVolumeClaim:
                claimName: quanta-dev-claim2
            - name: quanta-dev-claim3
              persistentVolumeClaim:
                claimName: quanta-dev-claim3
            - name: quanta-dev-claim4
              persistentVolumeClaim:
                claimName: quanta-dev-claim4
            - name: quanta-dev-claim5
              persistentVolumeClaim:
                claimName: quanta-dev-claim5
            - name: quanta-dev-claim6
              persistentVolumeClaim:
                claimName: quanta-dev-claim6
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: quanta-dev-claim0
      name: quanta-dev-claim0
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: quanta-dev-claim1
      name: quanta-dev-claim1
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: quanta-dev-claim2
      name: quanta-dev-claim2
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: quanta-dev-claim3
      name: quanta-dev-claim3
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: quanta-dev-claim4
      name: quanta-dev-claim4
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: quanta-dev-claim5
      name: quanta-dev-claim5
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: quanta-dev-claim6
      name: quanta-dev-claim6
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 100Mi
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      creationTimestamp: null
      name: net-dev
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  io.kompose.network/net-dev: "true"
      podSelector:
        matchLabels:
          io.kompose.network/net-dev: "true"
kind: List
metadata: {}

