#!/bin/bash

# Directory that contains the SubNode project (pom.xml is here, for example). This is the only
# hard-coded path, in the bash scripts
export PRJROOT=/home/clay/ferguson/Quantizr

# Directory where we put the final output image that the 'build.sh' script builds. (i.e. the output
# of the 'docker save' will go into this folder, and is the image ready for distrobution/installation)
export DOCKER_IMAGES_FOLDER=/home/clay/docker-images

# Should point to a script that exports these variable ${subnodePassword}
export SECRET_SCRIPT=../meta64Oak-private/secrets.sh

# Path where the log files generated by the running app get stored.
export SUBNODE_LOG_FOLDER=/home/clay/quantizr-tmp/log

# Path where the log files generated by the running app get stored.
export SUBNODE_LUCENE_FOLDER=/home/clay/quantizr-tmp/lucene

# Path that Quantizr app will use at runtime as it's temp folder
export SUBNODE_TMP_FOLDER=/home/clay/quantizr-tmp/tmp

export ipfs_data=/home/clay/.ipfs
export ipfs_staging=/home/clay/.ipfs/staging

# These two password variables need to put into your environment
# like by editing '/etc/environment' on linux which are the following:
#    subnodePassword

