# NOTE: These properties are overridable via command line arguments and/or environment variables, as well as the
# default assumption that you might have your secrets in a file named "../secrets/secrets.yaml" (outside the project),
# but you can look at `config.py` to see how the configuration is loaded.

# OpenAI
openai_api_key: "your-api-key"
openai_model: "gpt-4o"

# Anthropic
anth_api_key: "your-api-key"
anth_model: "claude-3-opus-20240229"

# Gemini
gemini_api_key: "your-api-key"
gemini_model: "gemini-1.5-pro" 

mode: "none"

ok_hal: ">"

# OPENAI = "openai"
# ANTHROPIC = "anth"
# GEMINI = "gemini"
ai_service: "anth"

scan_extensions: ".java, .py, .html, .htm, .ts, .scss, .md"
data_folder: "/home/clay/ai-agent-temp"

source_folder: "/home/clay/ferguson/Quanta Browser"

# The folders to include/exclude in the scan, relative to (i.e. contained within) the source_folder. In other words
# these folders will be directly concatenated to the source_folder to form the full paths to the folders to scan.
# If not specified, the entire project is scanned.
folders_to_include: ""
folders_to_exclude: "/nothing"