# NOTE: These properties are overridable via command line arguments and/or environment variables, as well as the
# default assumption that you might have your secrets in a file named "../secrets/secrets.yaml" (outside the project),
# but you can look at `config.py` to see how the configuration is loaded.

# OpenAI
openai_api_key: "your-api-key"
openai_model: "gpt-4o"

# Anthropic
anth_api_key: "your-api-key"
anth_model: "claude-3-opus-20240229"

# Gemini
gemini_api_key: "your-api-key"
gemini_model: "gemini-1.5-pro" 

mode: "none"
ai_service: "openai"
source_folder: "/home/clay/ferguson/Quantizr/QuantaAgent/test_project"
scan_extensions: ".java, .sql, .py, .html, .htm, .js, .ts, .css"
data_folder: "/home/clay/ai-agent-temp"
 

