version: '3.7'
services:
    mongo-distro: 
        hostname: mongo-host-distro
        networks:
            bridge:
                aliases:
                    - mongo-host-distro
                    
        # WARNING: volumes will not handle '~' character for home folder. Do not use.
        volumes:
            - '${MONGO_DATA}:/data/db'
            - '${MONGOD_CONF}:/etc/mongod.conf'

        command: mongod --config /etc/mongod.conf

        # # todo-0 (prod had this ports section. Need to verify it works in my new config files: dev & distro)
        # ports:
        #     - '${MONGO_PORT}:${MONGO_PORT}'

        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: ${adminPassword}

        # Always specify version of mongo. When it upgrades automatically there can be database issues that need to be resolved
        # and we don't want that happening unexpectedly
        image: mongo:4.0

    quanta-distro:
        image: ${DOCKER_IMAGE}
        build: 
            context: .
            args:
                PORT_SEC: "${PORT_SEC}"
                PORT: "${PORT}"
                PORT_DEBUG: "${PORT_DEBUG}"
                JAR_FILE: "${JAR_FILE}"
                XMS: "${XMS}"
                XMX: "${XMX}"
            dockerfile: ./dockerfile

        hostname: quanta-host
        networks:
            bridge:
                aliases:
                    - quanta-host

        volumes:
            - '${DATA_FOLDER}/docs:/docs'
            - '${DATA_FOLDER}/tmp:/tmp'
            - '${DATA_FOLDER}/log:/log'
            - '${DEPLOY_TARGET}/config:/config'
            - '/etc/letsencrypt/live/${quanta_domain}:/letsencrypt'

            # todo-0: why do we have this? Still needed?
            # This maps '/app' to be the current folder where you run docker from (where the yaml file is normally)
            - $PWD:/app
        ports:
            - '${HOST_PORT_SEC}:${PORT_SEC}'
            - '${HOST_PORT}:${PORT}'

            # Uncomment for debugging...
            #- '8000:8000'
        
        environment:
            logging.config: /log/logback.xml
            XMS: "${XMS}"
            XMX: "${XMX}"

            # ----- todo-0: I think these properties are all obsolete, but I'm leaving them for now
            JAR_FILE: "${JAR_FILE}"
            PORT: "${PORT}"
            PORT_SEC: "${PORT_SEC}"
            PORT_DEBUG: "${PORT_DEBUG}" 
            # ----- end paranoia

            mongoAdminPassword: "${adminPassword}"
            mongoSecurity: "true"

            # NOTE: '>-' removes all newline characters and makes one long string
            # Using '|' there instead would preserve the newlines after read in
            # The '-' after either of those removes any trailing newline
            testUserAccounts: >-
                FollowBot:${adminPassword}:${devEmail},
                adam:${testPassword}:${devEmail},
                bob:${testPassword}:${devEmail},
                cory:${testPassword}:${devEmail},
                dan:${testPassword}:${devEmail},
                eric:${testPassword}:${devEmail}
    
            # throttleTime: "0"
            spring.config.location: "classpath:/application.properties" 
            mongodb.host: "${MONGO_HOST}"
            mongodb.port: "${MONGO_PORT}" 

            instanceId: "prod"
            profileName: "prod"

            server.port: "${PORT_SEC}" 
            httpProtocol: "https" 
            metaHost: "${quanta_domain}" 
            
            allowFileSystemSearch: "false"
            actPubEnabled: "true"
            ipfsEnabled: "${ipfsEnabled}"
            spring.http.multipart.max-file-size: "200MB" 
            spring.http.multipart.max-request-size: "200MB" 
            spring.servlet.multipart.max-file-size: "200MB"
            spring.servlet.multipart.max-request-size: "200MB"
            adminDataFolder: "/tmp" 

            # Uncomment for debugging... (don't forget to open ufw firewall for port on server)
            JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,address=0.0.0.0:8000,server=y,suspend=n"
            
            ipfs.host: "http://ipfs-distro"
            ipfs.apiPort: "5001"
            ipfs.gatewayPort: "8080"

            security.require-ssl: "true" 
            server.ssl.key-store: "/letsencrypt/keystore.p12" 
            server.ssl.key-store-password: "${prodKeyStorePassword}" 
            server.ssl.keyStoreType: "PKCS12" 
            server.ssl.keyAlias: "tomcat" 

            mail.port: ""
            mail.user: "postmaster@quantizr.com"
            mail.password: "${emailPassword}" 
            mail.host: "smtp.mailgun.org" 
            mail.from: "admin@quanta.wiki"

        depends_on:
            - mongo-distro
        #     - ipfs-dev

networks:
    bridge:
