# WE include all of JRE which is huge but in the future we can do something like this:
# https://stackoverflow.com/questions/53669151/java-11-application-as-lightweight-docker-image

# The main (or only?) difference between this 'prod' dockerfile and the other docker file in the project
# is that this one has PORT_SEC(443/https), and the other only has PORT (80/http)

FROM openjdk:11-jre
LABEL maintainer="wclayf@gmail.com"

ARG PORT
ARG PORT_SEC
ARG PORT_DEBUG
ARG JAR_FILE
ARG XMS
ARG XMX

EXPOSE ${PORT}
EXPOSE ${PORT_SEC}
EXPOSE ${PORT_DEBUG}

# Docker Swarm Port (must be open to outside world)
EXPOSE 4001
# Swarm UDP; should be exposed to the public
EXPOSE 4001/udp

COPY ${JAR_FILE} app.jar
RUN sh -c 'touch app.jar' 

COPY ./entrypoint.sh entrypoint.sh
RUN ["chmod", "+x", "entrypoint.sh"]
ENTRYPOINT ["./entrypoint.sh"]

# We had this format for a long time, but then noticed IPFS container was failing finding /bin/bash so I moved to the simpler shell script command above
# ENTRYPOINT ["/bin/bash", "-c", "/quanta/entrypoint.sh"]

# This works too but it's more flexible to just put the commands in 'entrypoint.sh'
# ENTRYPOINT ["/bin/bash", "-c", "java -Xms${XMS} -Xmx${XMX} -Dloader.path=/loader-path -Djava.security.egd=file:/dev/./urandom -jar /quanta/app.jar"]
