brandingAppName: Quanta
brandingMetaContent: "Quanta: Social Media Micro-blogging Platform for the Fediverse!"

# Tip: This 'menu' property is seen in TypeScript JSON as an array of objects in 
# variable 'S.quanta.config'
#
# Links here can be full url, or node names, or "tab:tabName"

rhsAnonLinks:
  - name: "About Quanta"
    link: ":home"
  - name: "Explore Features"
    link: ":features"

menu:
  help:
    - name: "About Quanta"
      link: ":home"
    - name: "User Guide"
      link: ":user-guide"
    - name: "Features Overview"
      link: ":features"
    - name: "Watch Screencasts"
      link: ":screencast"
    - name: "Demo Content"
      link: ":demo-data"
      
    # - name: "separator"
    #   link: ""
    # - name: "News"
    #   link: ":news"
    # - name: "Podcasts"
    #   link: ":podcasts"
    # welp. This list went back to nothing, for now.
    # - name: "separator"
    #   link: ""
    # - name: "Fediverse"
    #   link: "tab:feedTab"

help:
  menu:
    account: |
      Account Node
      Navigates you to the root node of your account.

  nodeStats:
    dialog: |
      Node Stats
      This is a word frequency analysis of the top hashtags, mentions, and words in the text. Click one to search it.

  type:
    calculator:
      editor: |
        Calculator Type
        Calculator type allows Javascript. For security reasons, only the owner of a calculator node will see the results of the script run.
        
        Enter any valid JS and log output onto the node like this:
        
        ```
        var sum = 2 + 3;
        q.log("Hello world!");
        q.log("Two plus Three equals "+sum);
        ```
        The 'q.log' function is automatically available.

    friend:    
      editor: |
        Enter the name of a friend on the local server as something like *'bob'* (without quotes)
        
        or enter a Foreign Fediverse server user name formatted like this *'bob@domain.com'* (without quotes)
    
    friendsList: 
      render: |
        Friends List
        This node defines your list of friends, as it's subnodes (i.e. who you follow on the Fediverse or this server will be defined by the children of this node).
        
        Use the 'Add Friend' button to add a new friend, and their content will then show up in your Feed tab. Note: Adding a friend is the same as following someone.

  fediverse:
    feed: |
      Fediverse Feed
      This is your Fediverse *feed* that shows a reverse chronological stream of posts, from this server and/or other 
      federated servers. Use `Menu -> Settings -> Show Sensitive Content` to turn on/off NSFW materials.

      Use any 'Jump' button in the feed to go the the tree location of that post. 

  gettingStarted: |
    Getting Started
    After logged in: To create your first Social Media post, click the *'Feed'* tab, and then click *'New Post'*, 
    enter a messsage, and click *'Save'*
    
    --OR--
    
    Turn on *'Edit Mode'* by clicking the *pencil icon* on the right-hand side of the page. 
    This will allow you to start creating, editing, and sharing nodes. 
    
    #### Public Posts

    Any nodes you Share to 'Public' (using Share button on the Editor Dialog) will show up in everyone elses Feed tab automatically.
    
    #### Private Posts

    To share a node only to specific people, use the Share button on the node and add them. That will post to their feed and also if 
    they want they can use the 'direct link' to any node to go directly to it in the future without going thru their Feed tab.
    
    If you get lost, click the 'cylinder' icon to get back to your Account Node.
    To learn more click *'Site Nav &rarr; User Guide'* 
  
  sharing:
    dialog: |
      Node Sharing
      Configures who is allowed to see and/or append subnodes under this node.

      You can share to as many people as you want and they'll be able to see and reply (create subnodes).

      When sharing to 'Public' you can choose the 'Read-Only' option if you want to disable other users from being able to create 
      subnodes under.
      
      If you pick one of the 'Public' options then you don't need to specifically add any individual persons by name.

  search:
    dialog: |
      Search Tips

      The following tips apply for non-Regex option (Regex rules are separate):
      
      * To search for a multi-word phrase (or an exact match on a word) enclose it in double quotes.
      * To find all nodes that contain any of a list words enter the words with spaces between them
      * To exclude search results that contain some word, put a '-' (minus) right in front of the word (or right in front of a quoted string)
      * Normally searching will find *any* of the words you enter, however if you want to require *all* words to be found
        then enclose each word in a double quotes
      
  editor:
    dialog: |
      Node Editing Tips
      #### Images
      
      To display the node's attached image at a specific location in the content (rather than below the content, which is the default) you
      can embed `{{img}}` anywhere in the text, to mark where you want the image to appear.
      
      To make your attached image appear at upper left corner of the node with text wrapped around it, make your first line of 
      content text be {{imgUpperLeft}}. Similarly, to make your image at upper right of the node enter `{{imgUpperRight}}` as the first line.
      
      #### URL Previews
      
      To disable preview rendering for URLs either prefix them with an asterisk or surround in parenthesis like the following:
      
      ```
      * https://somewhere.com
      --or--
      (https://somewhere.com)
      ```
