brandingAppName: Quanta
brandingMetaContent: "Quanta: Social Media Micro-blogging Platform for the Fediverse!"
introSubtitle: Welcome to the Fediverse!
intro1: >- 
  Quanta is a decentralized and federated content management, social media, and publishing platform. 
  Join the Fediverse Revolution!
intro2:
