# NOTE: These properties are overridable via command line arguments and/or environment variables, as well as the
# default assumption that you might have your secrets in a file named "../secrets/secrets.yaml" (outside the project),
# but you can look at `config.py` to see how the configuration is loaded.

# OpenAI
openai_api_key: "your-api-key"
openai_model: "gpt-4o"

# XAI
xai_api_key: "your-api-key"
xai_model: "grok-beta"

# Anthropic
anth_api_key: "your-api-key"
anth_model: claude-3-7-sonnet-20250219

# Gemini
gemini_api_key: "your-api-key"
gemini_model: "gemini-1.5-pro" 

mode: "none"

# WARNING: Currently gemini doesn't seem to support Tool Calling, but I haven't started to investigate why yet.
#
# OPENAI = "openai" (supports Tool Calling)
# ANTHROPIC = "anth" (supports Tool Calling)
# GEMINI = "gemini"
# XAI = "xai"
ai_service: "openai"

scan_extensions: "py,html"
data_folder: "/home/clay/ai-agent-temp"

source_folder: "/home/clay/ferguson/Quantizr"

# Folders to include/exclude in the scan, relative to (i.e. contained within) the source_folder. In other words
# these folders will be directly concatenated to the source_folder to form the full paths to the folders to scan.
# If folders_to_include is not specified, the entire project is scanned. If folders_to_exclude is not specified, no
# folders are excluded.
folders_to_include: "/common,/QuantaGradio"
folders_to_exclude: ""