#!/bin/bash
# Purpose: Generator for mongo config files (mongod.conf). 
# Generates files by writing out what is basically 'template' text below, because the
# variables in the template get substituted during the 'cat' operation.

# gets the filename of the currently executing bash script.
THIS_FILE=`basename "$0"`

# ============================
# Generate mongod.conf
# ============================

echo "Generating ${MONGOD_CONF}"
cat > ${MONGOD_CONF} <<- EOM
# WARNING: This file is generated by ${THIS_FILE}
# Do not edit this file.

EOM

cat >> ${MONGOD_CONF} <<- EOM
net:
    port: ${MONGO_PORT}
    bindIp: ${MONGO_HOST}

security:
    authorization: enabled
EOM
