#!/bin/bash
# Purpose: Generator for mongo conf files

OUT_FILE=$1
THIS_FILE=`basename "$0"`

echo "Generating ${OUT_FILE}"
cat > ${OUT_FILE} <<- EOM
# WARNING: This file is generated by ${THIS_FILE}
# Do not edit this file.

EOM

cat >> ${OUT_FILE} <<- EOM
net:
    port: ${MONGO_PORT}
    bindIp: ${MONGO_HOST}

security:
    authorization: enabled
EOM
