#!/bin/bash
# Purpose: Generator for mongo conf files. This lets us generate a specific
# file by writing out what is basically 'template' text below, because the
# variables in the template do get substituted during the 'cat' operation.

OUT_FILE=${MONGOD_CONF}

# gets the filename of the currently executing bash script.
THIS_FILE=`basename "$0"`

echo "Generating ${OUT_FILE}"
cat > ${OUT_FILE} <<- EOM
# WARNING: This file is generated by ${THIS_FILE}
# Do not edit this file.

EOM

cat >> ${OUT_FILE} <<- EOM
net:
    port: ${MONGO_PORT}
    bindIp: ${MONGO_HOST}

security:
    authorization: enabled
EOM
