CREATE SEQUENCE user_accnt_SEQ INCREMENT 50 START 1;

/* rename id to user_id and user_id to mongo_id*/
CREATE TABLE user_accnt (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mongo_id VARCHAR(24) NOT NULL UNIQUE
);

CREATE SEQUENCE transaction_SEQ INCREMENT 50 START 1;

CREATE TABLE transaction (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES user_accnt(id),
    amt DECIMAL(14,6) NOT NULL, -- We store small fractions of a penny because of OpenAI small charges
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    trans_type CHAR(1) CHECK(trans_type IN ('C', 'D')), -- 'C' for credit, 'D' for debit
    desc_code VARCHAR(3) NOT NULL,
    detail JSONB
);
