CREATE SEQUENCE user_accnt_SEQ INCREMENT 50 START 1;

CREATE TABLE user_accnt (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mongo_id VARCHAR(24) NOT NULL UNIQUE,
    user_name VARCHAR(150) NOT NULL UNIQUE
);

CREATE SEQUENCE tran_SEQ INCREMENT 50 START 1;

CREATE TABLE tran (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_id INTEGER REFERENCES user_accnt(id) ON DELETE CASCADE,
    amt DECIMAL(14,6) NOT NULL, -- We store small fractions of a penny because of OpenAI small charges
    ts TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    tran_type CHAR(1) CHECK(tran_type IN ('C', 'D')), -- 'C' for credit, 'D' for debit
    desc_code VARCHAR(3) NOT NULL,
    detail JSONB,
    UNIQUE (user_id, ts) -- This line adds the unique constraint
);
