# Config file for `GitHub Pages`

title: Quanta
description: AI Powered Collaborative Documents
# remote_theme: pages-themes/midnight@v0.2.0
plugins:
  # - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-assets

# Include the custom CSS file
assets:
  css:
    - /assets/css/custom.css