# Config file for `GitHub Pages`

# theme: jekyll-theme-minimal
title: Quanta - AI Powered Collaborative Documents

# NOTE: Using this remote theme requires the plugin also (commented out)
# remote_theme: pages-themes/midnight@v0.2.0
plugins:
  # - jekyll-remote-theme # add this line to the plugins list if you already have one
  - jekyll-assets

# Include the custom CSS file
assets:
  css:
    - /assets/css/custom.css