FROM python:3.12.3-slim
LABEL maintainer="wclayf@gmail.com"
ARG QAI_HOST
ARG QAI_PORT

WORKDIR /app/common
COPY common .

WORKDIR /app/QuantaAI
COPY QuantaAI .

# Install the Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Run the uvicorn server (Note: The :app suffix after the script name is the variable name in the script which runs the FastAPI app)
CMD uvicorn quanta_ai:app --host ${QAI_HOST} --port ${QAI_PORT}