# NOTE: Don't try 'slim' jdk. It's missing the code for our captcha image generation
# and possibly other things
FROM openjdk:22
LABEL maintainer="wclayf@gmail.com"

ARG PORT
ARG PORT_SEC
ARG PORT_DEBUG
ARG XMS
ARG XMX

EXPOSE ${PORT}
EXPOSE ${PORT_SEC}
EXPOSE ${PORT_DEBUG}

COPY ./target/quanta-0.0.1-SNAPSHOT.jar app.jar
RUN sh -c 'touch app.jar' 

COPY ./entrypoint-distro.sh entrypoint-distro.sh
RUN ["chmod", "+x", "entrypoint-distro.sh"]
ENTRYPOINT ["./entrypoint-distro.sh"]

# ENTRYPOINT ["/bin/bash", "-c", "/quanta/entrypoint-distro.sh"]

# This works too but it's more flexible to just put the commands in 'entrypoint-distro.sh'
# ENTRYPOINT ["/bin/bash", "-c", "java -Xms${XMS} -Xmx${XMX} -Djava.security.egd=file:/dev/./urandom -jar /quanta/app.jar"]
